project:
  type: website
  output-dir: docs

website:
  title: "Keerthy Rangan's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CDCProject.qmd
        text: CDC Project
      - href: ProteinStructure.qmd
        text: Amyloid Structure Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



